### ISSUE TITLE
您好，我想问一下您使用什么样的摄像头运动跟踪系统？我想要标记真实轨迹，用其他方式如何能够契合代码对数据格式的要求？

### ISSUE THREAD

**Issue by Qi-le-le** [Huang-Chuan/MAINSvsMAGEKF#1]

**Comment by Huang-Chuan** [comment]
我们用的Qualysis的系统，摄像头是 [https://www.qualisys.com/cameras/arqus/]()。真实轨迹的数据格式就和data目录下的那些文件相同就好了。

**Comment by Qi-le-le** [comment]
谢谢您，十分感谢

**Comment by Qi-le-le** [comment]
您好，我是刚接触这个方向，不懂的地方有些多，想要再问一下您，如果说，我想要按照自己规定的轨迹采集磁场数据，那么对于真实轨迹的记录，能不能简化一些，不用这种基于摄像头的跟踪系统，这样的话，对于代码算法的实现或者最后精度的测量，影响大吗？

**Comment by Huang-Chuan** [comment]
你可以用自己的跟踪系统。这个算法不依赖真实轨迹，主要影响因素是IMU和磁力计的品质。

**Comment by Qi-le-le** [comment]
我是见您代码中参数的输入中有关于真实数据的参数，那我可不可以先不采集真实轨迹数据，就直接先仅利用IMU和磁力计采集的数据，看一下最后输出的效果，这样做能行不，对于代码的改动影响大吗？

**Comment by Qi-le-le** [comment]
我目前的设备条件有点局限

**Comment by Huang-Chuan** [comment]
你在使用的时候把settings里的pos_aiding选项关了就可以。

**Comment by Qi-le-le** [comment]
好的，十分感谢您

**Comment by Qi-le-le** [comment]
您好，我想问一下您，对磁力计数据进行校准的校准参数theta_all的数据是如何获取的？

**Comment by Huang-Chuan** [comment]
这部分需要用到[IMU和磁力计校准算法](https://arxiv.org/pdf/1601.05257)。

**Comment by Qi-le-le** [comment]
非常感谢您，我已经阅读了这篇论文，由于刚上手这方面的研究，对于该论文的方法实现没有彻底搞懂消化掉。我有一个不情之请，不知道您能否发我邮箱一下（sunshangqi8086@163.com)关于校准数据这部分的代码，供我参考学习，谢谢您！期待您的回复。

**Comment by Huang-Chuan** [comment]
这部分代码目前没有清理，所以不方便分享给你。

**Comment by Qi-le-le** [comment]
好的，谢谢，十分感谢您。
